// ============================================================
// Phoenix Platform — Evidence Fixtures
// PHX-PLATFORM-004 — Entity View & Audit Fixtures
// PHX-PLATFORM-005 — Evidence Traceability (expanded for full
// six-dimension coverage per sample assessment)
// ------------------------------------------------------------
// Representative mock EvidenceItem records for the sample
// assessments defined in sample-data.ts. Every item here is
// illustrative Alpha-build content — no real evidence, reviewer,
// or source document is attached to it.
//
// Evidence is keyed to the sample assessment IDs produced by
// api-adapters.ts's mapSampleAssetToAssessment (`${assetId}-assessment`),
// so getEvidenceItemsForAssessment(assessmentId) can filter this list
// directly without any additional joins.
//
// PHX-PLATFORM-005: each of the six sample assessments now carries
// one EvidenceItem per PBRS dimension (accuracy, compliance,
// brandAlignment, structure, consistency, completeness), so
// api-adapters.ts's mapSampleAssetToPBRSScoreRecord() can populate
// every PBRSDimensionScore.evidenceIds with at least one matching
// EvidenceItem id. This is presentation/traceability data only — it
// does not change any dimension's scored value.
// ============================================================

import type { EvidenceItem } from '@phoenix/core';
import { MOCK_OWNER_USER_ID, ownerUserIdForName } from '../mock-ids';

function iso(dateOnly: string): string {
  return `${dateOnly}T00:00:00Z`;
}

/**
 * Representative evidence covering all six PBRS dimensions across all six
 * sample assessments. Each block below corresponds to one sample asset from
 * sample-data.ts, in dimension order (accuracy, compliance, brandAlignment,
 * structure, consistency, completeness).
 */
export const EVIDENCE_ITEMS: EvidenceItem[] = [
  // ============================================================
  // ast-001 — Executive AI Brief (Certified) — owner S. Al-Farsi
  // ============================================================
  {
    id: 'evi-001',
    assessmentId: 'ast-001-assessment',
    type: 'Document',
    title: 'Q2 Board Briefing — Source Draft v3',
    note: 'Original AI-generated draft used as the scored source document for this assessment.',
    fileUrl: '/mock-evidence/ast-001-source-draft-v3.pdf',
    uploadedByUserId: ownerUserIdForName('S. Al-Farsi'),
    relatedDimension: 'accuracy',
    createdAt: iso('2026-06-27'),
    updatedAt: iso('2026-06-27'),
    deletedAt: null,
  },
  {
    id: 'evi-002',
    assessmentId: 'ast-001-assessment',
    type: 'ExternalLink',
    title: 'Compliance policy note — executive communications disclosure standard',
    note: 'Cross-checked against the executive communications disclosure standard; no restricted material referenced.',
    externalUrl: 'https://intranet.acme-enterprise.example/policies/executive-comms-disclosure',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'compliance',
    createdAt: iso('2026-06-27'),
    updatedAt: iso('2026-06-27'),
    deletedAt: null,
  },
  {
    id: 'evi-003',
    assessmentId: 'ast-001-assessment',
    type: 'Document',
    title: 'Brand guideline reference — Executive Voice Guide v1.4',
    note: 'Compared briefing tone and terminology against the executive voice guide.',
    fileUrl: '/mock-evidence/executive-voice-guide-v1-4.pdf',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'brandAlignment',
    createdAt: iso('2026-06-27'),
    updatedAt: iso('2026-06-27'),
    deletedAt: null,
  },
  {
    id: 'evi-004',
    assessmentId: 'ast-001-assessment',
    type: 'ReviewerNote',
    title: 'Reviewer comment — structure matches board template',
    note: 'Section order and heading structure match the standard board briefing template.',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'structure',
    createdAt: iso('2026-06-28'),
    updatedAt: iso('2026-06-28'),
    deletedAt: null,
  },
  {
    id: 'evi-005',
    assessmentId: 'ast-001-assessment',
    type: 'ReviewerNote',
    title: 'Reviewer sign-off — S. Al-Farsi',
    note: 'Verified tone and structure align with prior board briefings. No factual issues found on second pass.',
    uploadedByUserId: ownerUserIdForName('S. Al-Farsi'),
    relatedDimension: 'consistency',
    createdAt: iso('2026-06-28'),
    updatedAt: iso('2026-06-28'),
    deletedAt: null,
  },
  {
    id: 'evi-006',
    assessmentId: 'ast-001-assessment',
    type: 'ReviewerNote',
    title: 'Evidence checklist — all required sections present',
    note: 'Confirmed the briefing includes executive summary, financial highlights, risks, and next steps.',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'completeness',
    createdAt: iso('2026-06-28'),
    updatedAt: iso('2026-06-28'),
    deletedAt: null,
  },

  // ============================================================
  // ast-002 — HR Policy Summary (Business Ready) — owner M. Khoury
  // ============================================================
  {
    id: 'evi-007',
    assessmentId: 'ast-002-assessment',
    type: 'ReviewerNote',
    title: 'Human validation note — M. Khoury',
    note: 'Manually re-read the summary against the source policy PDF; language is accurate and the tone is appropriately neutral.',
    uploadedByUserId: ownerUserIdForName('M. Khoury'),
    relatedDimension: 'accuracy',
    createdAt: iso('2026-06-25'),
    updatedAt: iso('2026-06-25'),
    deletedAt: null,
  },
  {
    id: 'evi-008',
    assessmentId: 'ast-002-assessment',
    type: 'ExternalLink',
    title: 'Compliance policy note — Employment Standards reference',
    note: 'Cross-referenced against the current employment standards policy to confirm the summary omits no mandatory clause.',
    externalUrl: 'https://intranet.acme-enterprise.example/policies/employment-standards',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'compliance',
    createdAt: iso('2026-06-24'),
    updatedAt: iso('2026-06-24'),
    deletedAt: null,
  },
  {
    id: 'evi-009',
    assessmentId: 'ast-002-assessment',
    type: 'Document',
    title: 'Brand guideline reference — internal policy tone standard',
    note: 'Confirmed the summary uses the approved neutral, plain-language register for internal HR communications.',
    fileUrl: '/mock-evidence/hr-policy-tone-standard.pdf',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'brandAlignment',
    createdAt: iso('2026-06-24'),
    updatedAt: iso('2026-06-24'),
    deletedAt: null,
  },
  {
    id: 'evi-010',
    assessmentId: 'ast-002-assessment',
    type: 'ReviewerNote',
    title: 'Reviewer comment — structure check against policy template',
    note: 'Section headings and clause numbering follow the standard HR policy summary template.',
    uploadedByUserId: ownerUserIdForName('M. Khoury'),
    relatedDimension: 'structure',
    createdAt: iso('2026-06-25'),
    updatedAt: iso('2026-06-25'),
    deletedAt: null,
  },
  {
    id: 'evi-011',
    assessmentId: 'ast-002-assessment',
    type: 'ReviewerNote',
    title: 'Reviewer comment — consistent with prior HR summaries',
    note: 'Terminology and formatting match the last three published HR policy summaries.',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'consistency',
    createdAt: iso('2026-06-25'),
    updatedAt: iso('2026-06-25'),
    deletedAt: null,
  },
  {
    id: 'evi-012',
    assessmentId: 'ast-002-assessment',
    type: 'ReviewerNote',
    title: 'Evidence checklist — completeness confirmed',
    note: 'All mandatory clauses from the source policy are represented in the summary.',
    uploadedByUserId: ownerUserIdForName('M. Khoury'),
    relatedDimension: 'completeness',
    createdAt: iso('2026-06-25'),
    updatedAt: iso('2026-06-25'),
    deletedAt: null,
  },

  // ============================================================
  // ast-003 — Board Report Draft (In Review) — owner S. Al-Farsi
  // ============================================================
  {
    id: 'evi-013',
    assessmentId: 'ast-003-assessment',
    type: 'Document',
    title: 'Board Report Draft — Source Output',
    note: 'Raw AI-generated draft submitted for assessment prior to reviewer pass.',
    fileUrl: '/mock-evidence/ast-003-board-report-draft.docx',
    uploadedByUserId: ownerUserIdForName('S. Al-Farsi'),
    relatedDimension: 'accuracy',
    createdAt: iso('2026-06-29'),
    updatedAt: iso('2026-06-29'),
    deletedAt: null,
  },
  {
    id: 'evi-014',
    assessmentId: 'ast-003-assessment',
    type: 'ExternalLink',
    title: 'Compliance policy note — board reporting disclosure standard',
    note: 'Checked draft financial figures against the disclosure standard for board-facing reports.',
    externalUrl: 'https://intranet.acme-enterprise.example/policies/board-reporting-disclosure',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'compliance',
    createdAt: iso('2026-06-29'),
    updatedAt: iso('2026-06-29'),
    deletedAt: null,
  },
  {
    id: 'evi-015',
    assessmentId: 'ast-003-assessment',
    type: 'Document',
    title: 'Brand guideline reference — Executive Voice Guide v1.4',
    note: 'Draft tone compared against the executive voice guide; largely aligned pending revision.',
    fileUrl: '/mock-evidence/executive-voice-guide-v1-4.pdf',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'brandAlignment',
    createdAt: iso('2026-06-30'),
    updatedAt: iso('2026-06-30'),
    deletedAt: null,
  },
  {
    id: 'evi-016',
    assessmentId: 'ast-003-assessment',
    type: 'ReviewerNote',
    title: 'Reviewer comment — pending revision',
    note: 'Section 3 needs a clearer risk framing before this can move to Approved. Flagging for a follow-up pass.',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'structure',
    createdAt: iso('2026-07-01'),
    updatedAt: iso('2026-07-01'),
    deletedAt: null,
  },
  {
    id: 'evi-017',
    assessmentId: 'ast-003-assessment',
    type: 'ReviewerNote',
    title: 'Reviewer comment — terminology consistency',
    note: 'Some department names in Section 2 do not match the current org chart naming; flagged for correction.',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'consistency',
    createdAt: iso('2026-07-01'),
    updatedAt: iso('2026-07-01'),
    deletedAt: null,
  },
  {
    id: 'evi-018',
    assessmentId: 'ast-003-assessment',
    type: 'ReviewerNote',
    title: 'Evidence checklist — in progress',
    note: 'Financial highlights and risk sections present; appendix of supporting data still pending from Finance.',
    uploadedByUserId: ownerUserIdForName('S. Al-Farsi'),
    relatedDimension: 'completeness',
    createdAt: iso('2026-07-01'),
    updatedAt: iso('2026-07-01'),
    deletedAt: null,
  },

  // ============================================================
  // ast-004 — Sustainability Claims Review (Needs Improvement) — owner R. Haddad
  // ============================================================
  {
    id: 'evi-019',
    assessmentId: 'ast-004-assessment',
    type: 'Document',
    title: 'Sustainability Claims Review — Source Output',
    note: 'Original AI-generated draft submitted for compliance review.',
    fileUrl: '/mock-evidence/ast-004-sustainability-claims-draft.docx',
    uploadedByUserId: ownerUserIdForName('R. Haddad'),
    relatedDimension: 'accuracy',
    createdAt: iso('2026-06-29'),
    updatedAt: iso('2026-06-29'),
    deletedAt: null,
  },
  {
    id: 'evi-020',
    assessmentId: 'ast-004-assessment',
    type: 'ExternalLink',
    title: 'Legal source reference — advertising claims regulation',
    note: 'Referenced against the applicable advertising-claims regulation to check substantiation requirements.',
    externalUrl: 'https://intranet.acme-enterprise.example/legal/advertising-claims-guidance',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'compliance',
    createdAt: iso('2026-06-29'),
    updatedAt: iso('2026-06-29'),
    deletedAt: null,
  },
  {
    id: 'evi-021',
    assessmentId: 'ast-004-assessment',
    type: 'ReviewerNote',
    title: 'Reviewer comment — R. Haddad',
    note: 'Several sustainability claims lack a cited source. Recommend returning to the requester for substantiation before re-scoring.',
    uploadedByUserId: ownerUserIdForName('R. Haddad'),
    relatedDimension: 'compliance',
    createdAt: iso('2026-06-30'),
    updatedAt: iso('2026-06-30'),
    deletedAt: null,
  },
  {
    id: 'evi-022',
    assessmentId: 'ast-004-assessment',
    type: 'Document',
    title: 'Brand guideline reference — sustainability messaging standard',
    note: 'Draft claims language checked against the approved sustainability messaging standard.',
    fileUrl: '/mock-evidence/sustainability-messaging-standard.pdf',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'brandAlignment',
    createdAt: iso('2026-06-30'),
    updatedAt: iso('2026-06-30'),
    deletedAt: null,
  },
  {
    id: 'evi-023',
    assessmentId: 'ast-004-assessment',
    type: 'ReviewerNote',
    title: 'Reviewer comment — structure needs a substantiation appendix',
    note: 'Recommend adding a dedicated sources/substantiation appendix rather than inline claims only.',
    uploadedByUserId: ownerUserIdForName('R. Haddad'),
    relatedDimension: 'structure',
    createdAt: iso('2026-06-30'),
    updatedAt: iso('2026-06-30'),
    deletedAt: null,
  },
  {
    id: 'evi-024',
    assessmentId: 'ast-004-assessment',
    type: 'ReviewerNote',
    title: 'Reviewer comment — terminology inconsistent with prior filings',
    note: 'Some sustainability terms diverge from language used in last year\u2019s filing; needs alignment.',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'consistency',
    createdAt: iso('2026-06-30'),
    updatedAt: iso('2026-06-30'),
    deletedAt: null,
  },
  {
    id: 'evi-025',
    assessmentId: 'ast-004-assessment',
    type: 'ReviewerNote',
    title: 'Evidence checklist — substantiation gaps',
    note: 'Missing citations for at least three claims; checklist cannot be marked complete until resolved.',
    uploadedByUserId: ownerUserIdForName('R. Haddad'),
    relatedDimension: 'completeness',
    createdAt: iso('2026-06-30'),
    updatedAt: iso('2026-06-30'),
    deletedAt: null,
  },

  // ============================================================
  // ast-005 — Marketing Campaign Copy (Business Ready) — owner L. Nasser
  // ============================================================
  {
    id: 'evi-026',
    assessmentId: 'ast-005-assessment',
    type: 'Document',
    title: 'Marketing Campaign Copy — Source Output',
    note: 'Original AI-generated campaign copy submitted across three channel variants.',
    fileUrl: '/mock-evidence/ast-005-campaign-copy-source.docx',
    uploadedByUserId: ownerUserIdForName('L. Nasser'),
    relatedDimension: 'accuracy',
    createdAt: iso('2026-06-26'),
    updatedAt: iso('2026-06-26'),
    deletedAt: null,
  },
  {
    id: 'evi-027',
    assessmentId: 'ast-005-assessment',
    type: 'ExternalLink',
    title: 'Compliance policy note — advertising claims self-check',
    note: 'Verified copy makes no unsubstantiated product claims per the advertising self-check policy.',
    externalUrl: 'https://intranet.acme-enterprise.example/policies/advertising-self-check',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'compliance',
    createdAt: iso('2026-06-26'),
    updatedAt: iso('2026-06-26'),
    deletedAt: null,
  },
  {
    id: 'evi-028',
    assessmentId: 'ast-005-assessment',
    type: 'Document',
    title: 'Brand guideline reference — Voice & Tone v2.1',
    note: 'Compared campaign copy against the current brand voice and tone guide for terminology and register.',
    fileUrl: '/mock-evidence/brand-voice-tone-guide-v2-1.pdf',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'brandAlignment',
    createdAt: iso('2026-06-26'),
    updatedAt: iso('2026-06-26'),
    deletedAt: null,
  },
  {
    id: 'evi-029',
    assessmentId: 'ast-005-assessment',
    type: 'ReviewerNote',
    title: 'Reviewer comment — structure matches channel templates',
    note: 'Each channel variant follows the approved copy-block structure for that placement.',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'structure',
    createdAt: iso('2026-06-27'),
    updatedAt: iso('2026-06-27'),
    deletedAt: null,
  },
  {
    id: 'evi-030',
    assessmentId: 'ast-005-assessment',
    type: 'ReviewerNote',
    title: 'Human validation note — L. Nasser',
    note: 'Copy reads on-brand across all three channel variants. Approved for Business Ready status.',
    uploadedByUserId: ownerUserIdForName('L. Nasser'),
    relatedDimension: 'consistency',
    createdAt: iso('2026-06-27'),
    updatedAt: iso('2026-06-27'),
    deletedAt: null,
  },
  {
    id: 'evi-031',
    assessmentId: 'ast-005-assessment',
    type: 'ReviewerNote',
    title: 'Evidence checklist — all channel variants present',
    note: 'Confirmed copy exists for email, social, and landing-page placements as required by the brief.',
    uploadedByUserId: ownerUserIdForName('L. Nasser'),
    relatedDimension: 'completeness',
    createdAt: iso('2026-06-27'),
    updatedAt: iso('2026-06-27'),
    deletedAt: null,
  },

  // ============================================================
  // ast-006 — Legal Risk Memo (Draft) — owner T. Rahim
  // ============================================================
  {
    id: 'evi-032',
    assessmentId: 'ast-006-assessment',
    type: 'Document',
    title: 'Legal Risk Memo — Source Output',
    note: 'Initial AI-drafted memo submitted alongside the assessment request. Evidence collection in progress.',
    fileUrl: '/mock-evidence/ast-006-legal-risk-memo-draft.docx',
    uploadedByUserId: ownerUserIdForName('T. Rahim'),
    relatedDimension: 'accuracy',
    createdAt: iso('2026-07-02'),
    updatedAt: iso('2026-07-02'),
    deletedAt: null,
  },
  {
    id: 'evi-033',
    assessmentId: 'ast-006-assessment',
    type: 'ExternalLink',
    title: 'Legal source reference — prior precedent memo',
    note: 'Linked to the prior precedent memo this draft is modeled on, for cross-reference during scoring.',
    externalUrl: 'https://intranet.acme-enterprise.example/legal/precedent-memos/2025-114',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'compliance',
    createdAt: iso('2026-07-03'),
    updatedAt: iso('2026-07-03'),
    deletedAt: null,
  },
  {
    id: 'evi-034',
    assessmentId: 'ast-006-assessment',
    type: 'ReviewerNote',
    title: 'Reviewer comment — tone review pending',
    note: 'Brand/tone review against the legal-communications style note has not yet started.',
    uploadedByUserId: ownerUserIdForName('T. Rahim'),
    relatedDimension: 'brandAlignment',
    createdAt: iso('2026-07-03'),
    updatedAt: iso('2026-07-03'),
    deletedAt: null,
  },
  {
    id: 'evi-035',
    assessmentId: 'ast-006-assessment',
    type: 'ReviewerNote',
    title: 'Reviewer comment — structure follows memo template',
    note: 'Initial read confirms the memo follows the standard issue/analysis/recommendation structure.',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'structure',
    createdAt: iso('2026-07-03'),
    updatedAt: iso('2026-07-03'),
    deletedAt: null,
  },
  {
    id: 'evi-036',
    assessmentId: 'ast-006-assessment',
    type: 'ReviewerNote',
    title: 'Reviewer comment — consistency check not yet started',
    note: 'Cross-reference against related legal memos is queued behind the precedent-memo comparison.',
    uploadedByUserId: MOCK_OWNER_USER_ID,
    relatedDimension: 'consistency',
    createdAt: iso('2026-07-03'),
    updatedAt: iso('2026-07-03'),
    deletedAt: null,
  },
  {
    id: 'evi-037',
    assessmentId: 'ast-006-assessment',
    type: 'ReviewerNote',
    title: 'Evidence checklist — draft stage',
    note: 'Source draft and one precedent reference collected so far; additional evidence still to be gathered.',
    uploadedByUserId: ownerUserIdForName('T. Rahim'),
    relatedDimension: 'completeness',
    createdAt: iso('2026-07-03'),
    updatedAt: iso('2026-07-03'),
    deletedAt: null,
  },
];

/** Returns evidence for one assessment, newest first — used by api-client.ts's getEvidenceItems(). */
export function getEvidenceItemsForAssessment(assessmentId: string): EvidenceItem[] {
  return EVIDENCE_ITEMS.filter((item) => item.assessmentId === assessmentId).sort((a, b) =>
    a.createdAt < b.createdAt ? 1 : -1
  );
}
